export default {
    USER_GET: 'USER_GET',
    CURRENT_USER_GET: 'CURRENT_USER_GET',
    CURRENT_USER_ASYNC: 'CURRENT_USER_ASYNC',
    CURRENT_USER_CONNECTED: 'CURRENT_USER_CONNECTED',
    CURRENT_USER_JOINED: 'CURRENT_USER_JOINED',
};
